### ISSUE TITLE
Video not supported

### ISSUE THREAD

**Issue by Jetrom17** [Sketchware-Pro/Sketchware-Pro-Website#56]
![IMG_20241009_114427_203.jpg](https://github.com/user-attachments/assets/3fd9cfff-d038-49d2-a98c-988bf352c221)

![Screenshot_20241009-125724.png](https://github.com/user-attachments/assets/9abf0584-9864-476a-b04a-ee0b33d27fd8)

- [ ] Fix the implementation of web content.

**Comment by NiceSapien** [comment]
fixed.
